title: "Jaya Priya Gudapati - Cloud Engineer Portfolio"
description: "Cloud Engineer | M.S. in Computer Science | AWS & DevOps Enthusiast"
author: "Jaya Priya Gudapati"
theme: jekyll-theme-minimal

# Set the background color of the page
background: "#f4f4f9"  # Light grey background for the page

# Set the color of the headings
heading_font_color: "#2e3a59"  # Dark blue for headings

# Set text color
text_color: "#333"  # Dark grey for body text

# Set the link color
link_color: "#1a73e8"  # Blue color for links

# Configure the layout
layout: default

# Font settings (optional)
font:
  - "Roboto"
  - "Arial"


# Exclude unnecessary elements
exclude:
  - "README.md"  # Exclude the README file from being processed as content
