
title: "Jaya Priya Gudapati's GitHub Profile"
theme: "jekyll-theme-minimal"
display_profile_picture: true
social_links:
  - platform: LinkedIn
    url: [https://www.linkedin.com/in/priya-gudapati]
  - platform: Portfolio
    url: [your portfolio URL]
